name = "tabletop-tales"
main = "functions/api/[[route]].ts"
compatibility_date = "2024-11-01"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "tabletop-tales-db"
# Run `wrangler d1 create tabletop-tales-db` and paste the database_id here
database_id = "bacbc6fa-7ff5-4279-81b7-07b44ec8e80e"
